imageCredentials:
  clientsecret:
    registry: docker.yuuvis.org
    username: PLACEUSERNAMEHERE
    password: PLACEPASSWORDHERE 

yuuvis:
  image:
    imagePullPolicy: Always
  configservice:
    url: http://configservice/config
  livenessProbe:
    enable: false
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 10
  readinessProbe:
    enable: true
    initialDelaySeconds: 0
    periodSeconds: 30
    timeoutSeconds: 5
  client:
    apiweb:
      dockerImage: docker.yuuvis.org/yuuvis/api-web:2020-07-08
      initContainerImage: docker.yuuvis.org/yuuvis/helper/create-selfsigned-cert:latest
      profiles: prod,docker,kubernetes
      containerPort: 7550
      port: 7550
      targetPort: 7550
      port80: 80
      instances: 1
      java:
        maxHeap: -Xmx128m
    userservice:
      dockerImage: docker.yuuvis.org/yuuvis/userservice:2020-07-08
      initContainerImage: docker.yuuvis.org/yuuvis/helper/init-helper:latest
      profiles: postgres,userservice
      containerPort: 8080
      port: 80
      targetPort: 8080
      instances: 1
      java:
        maxHeap: -Xmx128m
      database:
        name: erebus
        user: postgres
        password: optimal
        address: postgresql.infrastructure
      userseriveyml: |
        keycloak.server: http://keycloak-http.infrastructure/auth
        keycloak.admin.username: keycloak
        keycloak.admin.password: optimal
    client:
      dockerImage: docker.yuuvis.org/yuuvis/client:2020-07-08
      instances: 1
      containerPort: 80
      port: 80
      targetPort: 80
    custom:
      dockerImage: docker.yuuvis.org/yuuvis/client:2020-07-08
      instances: 1
      containerPort: 80
      port: 80
      targetPort: 80
    viewer:
      dockerImage: docker.yuuvis.org/yuuvis/viewerservice:2020-07-08
      instances: 1
      port: 9000
      targetPort: 9000
      containerPort: 9000
      port80: 80
        
initContainer:
  command: "until wget -q --spider http://configservice/manage/health; do echo waiting for configservice; sleep 11; done;"
