apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: contentanalyzer
    k8s-app: contentanalyzer-gateway-metrics
    yuuvis: "true"
  name: contentanalyzer
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.contentanalyzer.port}}
  selector:
    name: contentanalyzer
  type: ClusterIP