apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    yuuvis: "true"
    name: api-web
  name: api-web
spec:
  ports:
  - name: http
    port: {{.Values.yuuvis.client.apiweb.port80}}
    protocol: TCP
    targetPort: {{.Values.yuuvis.client.apiweb.targetPort}}
  selector:
    name: api-web
  type: ClusterIP
