apiVersion: v1
data:
  init.bash: "#!/bin/bash\n\nuntil wget -q --spider http://configservice/manage/health;
    do echo waiting for configservice; sleep 11; done;\necho 'test if schema exists'\ngetschema=$(curl
    -s -o /dev/null -w \"%{http_code}\" \"http://configservice/api/resources/schema.xml/path/apps|client|system\")\nif
    [ \"$getschema\" = \"404\" ]\nthen\n        echo \"must create\"\n\t\tcurl -POST
    -F \"resource=@/yuuvis/data/schema.xml\" \"http://configservice/api/resources/schema.xml/path/apps|client|system\"\n\n\t\tcurl -POST
    -F \"resource=@/yuuvis/data/i18n_de.json\" \"http://configservice/api/resources/i18n_de.json/path/apps|api-web|text\"\n\n\t\tcurl -POST
    -F \"resource=@/yuuvis/data/i18n_en.json\" \"http://configservice/api/resources/i18n_en.json/path/apps|api-web|text\"\nelse\n
    \       echo \"app client schema already exists\"\nfi\n"
kind: ConfigMap
metadata:
  name: apiwebinit
