apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    yuuvis: "true"
    name: client
  name: client
spec:
  ports:
  - name: http
    port: {{.Values.yuuvis.client.client.port}}
    protocol: TCP
    targetPort: {{.Values.yuuvis.client.client.targetPort}}
  selector:
    name: client
  type: ClusterIP