apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    name: custom
    yuuvis: "true"
  name: custom
spec:
  ports:
  - name: http
    port: {{.Values.yuuvis.client.custom.port}}
    protocol: TCP
    targetPort: {{.Values.yuuvis.client.custom.targetPort}}
  selector:
    name: custom
  type: ClusterIP