apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    yuuvis: "true"
    name: userservice
  name: userservice
spec:
  ports:
  - name: http
    port: {{.Values.yuuvis.client.userservice.port}}
    protocol: TCP
    targetPort: {{.Values.yuuvis.client.userservice.targetPort}}
  selector:
    name: userservice
  type: ClusterIP