apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    yuuvis: "true"
    name: viewer
  name: viewer
spec:
  ports:
  - name: http
    port: {{.Values.yuuvis.client.viewer.port80}}
    protocol: TCP
    targetPort: {{.Values.yuuvis.client.viewer.targetPort}}
  selector:
    name: viewer
  type: ClusterIP