apiVersion: v1
kind: Service
metadata:
  labels:
    name: keycloak-https
  name: keycloak-https
spec:
  ports:
  - name: https
    port: 443
    targetPort: {{.Values.keycloak.targetPort}}
    nodePort: {{.Values.keycloak.nodePort}}
  selector:
    app.kubernetes.io/instance: {{.Release.Namespace}}
    app.kubernetes.io/name: keycloak
  type: NodePort