apiVersion: batch/v1
kind: Job
metadata:
  name: keycloakaddrole-yuuvis
  labels:
    app: keycloakaddrole
  annotations:
    reason: "https://issues.jboss.org/browse/KEYCLOAK-4923"
spec:
  template:
    spec:
      containers:
      - name: keycloakaddrole-yuuvis
        image: jboss/keycloak:{{.Values.keycloak.keycloak.image.tag}}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["/yuuvis/script/keycloakAddRoleToClient.bash"]
        volumeMounts:
        - mountPath: /yuuvis/script/keycloakAddRoleToClient.bash
          name: initscript
          subPath: keycloakAddRoleToClient.bash
        - mountPath: /var/run/secrets/yuuvis/
          name: keycloak-tls-selfsigned
      volumes:
      - configMap:
          name: keycloakaddroletoclient
        name: initscript
      - name: keycloak-tls-selfsigned
        secret:
          defaultMode: 420
          secretName: keycloak-selfsigned-tls-secret
      restartPolicy: OnFailure
