apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb
data:
  create_enaio_dbs.sql: |
    CREATE DATABASE yuuvis;
    CREATE USER yuuvis WITH ENCRYPTED PASSWORD 'optimal';
    GRANT ALL PRIVILEGES ON DATABASE yuuvis TO yuuvis;
    CREATE DATABASE keycloak;
    CREATE USER keycloak WITH ENCRYPTED PASSWORD 'optimal';
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;